### PR TITLE
[Fixes #241] Rename .env file

### LINKED ISSUE #241: Rename .env file
Users will probably customize vars in `.env`, so we don't want such a file to be stored in git repos.
If private info are hidden in the stored version, we'll get conflict at every git pull.
Furthermore, if the vanilla .env changes (vars added, etc), it will be difficult to perform a diff to find out what's changed.

- [ ] move `.env` to `.env_sample`
- [ ] update doc

### PR DESCRIPTION
**Pull request by marthamareal**

### CODE REVIEW

**Comment by giohappy** [comment]
I would replace the secrets with asterisks inside the nev sample, and say to set valid values for these settings inside the docs.
Otherwise most of the deployments will end by using the same secrets.

What do you think @etj?

**Comment by giohappy** [comment]
@marthamareal for the Django secret key we could adopt the option from the [startproject](https://docs.djangoproject.com/en/3.2/ref/django-admin/#startproject) command to obatin a random key at build time.
I guess we can do something like:

`SECRET_KEY='{{secret_key}}'` [here](https://github.com/GeoNode/geonode-project/blob/master/.env#L165)

btw we still have the problem with the OAUTH2 secrets, that must be set manually.

**Comment by marthamareal** [comment]
> @marthamareal for the Django secret key we could adopt the option from the [startproject](https://docs.djangoproject.com/en/3.2/ref/django-admin/#startproject) command to obatin a random key at build time. I guess we can do something like:
> 
> `SECRET_KEY='{{secret_key}}'` [here](https://github.com/GeoNode/geonode-project/blob/master/.env#L165)
> 

@giohappy  I have updated the PR and added the command to randomly generate the secrete key in the ReadMe

**Comment by marthamareal** [comment]
> btw we still have the problem with the OAUTH2 secrets, that must be set manually.

should we also use placeholders in variables `OAUTH2_CLIENT_ID` and `OAUTH2_CLIENT_SECRET`

**Comment by giohappy** [comment]
>should we also use placeholders in variables OAUTH2_CLIENT_ID and OAUTH2_CLIENT_SECRET

When I say secrets I mean any private information. So yes, OAUTH2 for sure. A note must be added to the README to remind to assigna  value to the .env file for these settings.

**Comment by marthamareal** [comment]
> > should we also use placeholders in variables OAUTH2_CLIENT_ID and OAUTH2_CLIENT_SECRET
> 
> When I say secrets I mean any private information. So yes, OAUTH2 for sure. A note must be added to the README to remind to assigna value to the .env file for these settings.

I have updated the variables also `DEFAULT_FROM_EMAIL` inclusive.

**Review by giohappy — APPROVED** [review]

**Pull request merged**
