### PR TITLE
 - Settings and Local Settings updated with Master branch (2.9.x) new options

### PR DESCRIPTION
**Pull request by afabiani**

### CODE REVIEW

**Comment by francbartoli** [comment]
As recently we switched from the old mercator should not there be 3857 [here](https://github.com/GeoNode/geonode-project/pull/28/files#diff-4f4c55450c39ce510cb2d3646b9b3301R219)?

Sorry I cannot review because I've not write access :(

**Comment by francbartoli** [comment]
Wondering also if 2.7.x branch should be provided given the fact it is now the most stable version. What do you think @afabiani?

**Comment by afabiani** [comment]
@francbartoli 

- Write access given

- About EPSG, ok, I'm going to update it

- About 2.7.x yes, I agree. We should backport some new features from master first. I'm going to prepare a PR for 2.7.x also.

**Comment by francbartoli** [comment]
thanks @afabiani

**Review by francbartoli — APPROVED** [review]

**Comment by ingenieroariel** [comment]
My preference is to have geonode-project just have <project_name>.settings and not import geonode.settings or use the local_settings option.

The reasons for this is to simplify users customizations by not making them look in 3 different locations.

My vote is -0 on this change. (Not fully agree but will not block the merge)

**Comment by francbartoli** [comment]
@afabiani does [2.9.x-rev](https://github.com/GeoNode/geonode-project/tree/2.9.x-rev) lead to **2.7.x** by backporting an excerpt of those new features?

**Comment by afabiani** [comment]
@francbartoli yes, just removing social auth and monitoring stuff (unless we backport this stuff on 2.7.x in the meantime)

**Pull request merged**
