### PR TITLE
Update docker-purge.sh for update

### PR DESCRIPTION
**Pull request by vmendezm**
Need to change permission in new version: run sudo chmod 666 /var/run/docker.sock

### CODE REVIEW

**Review by afabiani — APPROVED** [review]

**Comment by t-book** [comment]
@vmendezm @afabiani Honestly I'm not really happy with this change. In my opinion, permissions should be set by admin/users but not scripts. Further, the path to the socket can change. @vmendezm can you share the error you've run into?

**Comment by vmendezm** [comment]
Hey @t-book, the error was:

`Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Get http://%2Fvar%2Frun%2Fdocker.sock/v1.40/containers/json: dial unix /var/run/docker.sock: connect: permission denied`

**Comment by t-book** [comment]
Wouldn't it be cleaner to add the user in question to the docker group which should grant permissions on the socket?

`sudo usermod -aG docker $USER`

Which for me is a step when I setup docker. 

Sorry that I'm picky here but file permissions are always a big security risk. It just does not feel right to change here something "behind the scenes" (without letting the user know that it is happening)

**Comment by vmendezm** [comment]
@t-book 

Yes, that was the first thing that I did but my user was already in the 'docker’ group. So, I retry it with no success.
This was the only solution that I find.

**Comment by t-book** [comment]
Do you by chance remember the chmod permissions of the docker socket before you've changed them?

**Comment by t-book** [comment]
So I've checked this on a fresh Ubuntu 20.04 installation. The socket had by default 660

`stat -c %a /var/run/docker.sock` 

which allowed all members of the docker group to interact with the socket. My guess is your socket might had something more strict like 600 BUT @vmendezm  this might be the install we did together :)) ? So it is a fresh install as well. Let's skip the discussion for now. I will suggest a warning when running the command with another PR.

**Comment by vmendezm** [comment]
@t-book Sorry, I did not write down this information, but I guess you are right.

And yes, indeed, It's our install.

**Comment by afabiani** [comment]
Going to revert

**Pull request merged**
