### PR TITLE
Create docker-compose.development.override.yml

### PR DESCRIPTION
**Pull request by t-book**
Restored the file.

### CODE REVIEW

**Comment by francbartoli** [comment]
In the `entrypoint.sh` I have something similar to this:

```shell
...
echo DOCKER_ENV=$DOCKER_ENV >> /usr/src/mygeonode/invoke.log

if [ -z ${DOCKER_ENV} ] || [ ${DOCKER_ENV} = "development" ]
then

    echo "Executing standard Django server $cmd for Development"

    /usr/local/bin/invoke prepare >> /usr/src/mygeonode/invoke.log
    echo "prepare task done"

    /usr/local/bin/invoke fixtures >> /usr/src/mygeonode/invoke.log
    echo "fixture task done"

    echo "refresh static data"
    /usr/local/bin/invoke statics >> /usr/src/mygeonode/invoke.log
    echo "static data refreshed"

    echo "compile locale messages"
    /usr/local/bin/invoke messages >> /usr/src/mygeonode/invoke.log
    echo "locale messages compiled"

    /usr/local/bin/invoke waitforgeoserver >> /usr/src/mygeonode/invoke.log
    echo "waitforgeoserver task done"

    /usr/local/bin/invoke geoserverfixture >> /usr/src/mygeonode/invoke.log
    echo "geoserverfixture task done"

    /usr/local/bin/invoke updateadmin >> /usr/src/mygeonode/invoke.log
    echo "updateadmin task done"

else

    if [ ${IS_CELERY} = "true" ]  || [ ${IS_CELERY} = "True" ]
...
```

**Review by francbartoli — CHANGES_REQUESTED** [review]
Also around here https://github.com/GeoNode/geonode-project/blob/2.10.x/tasks.py#L96 you should define this below:

```shell
    ctx.run("echo export DOCKER_ENV=\
{docker_env} >> {override_fn}".format(**envs), pty=True)
```

**Comment by t-book** [comment]
@francbartoli do you still have those files locally? If so I think it would be easiest if you could just push them again. Otherwise, I will try to find some time this week to redo what you suggest. Thanks!

**Comment by francbartoli** [comment]
> @francbartoli do you still have those files locally? If so I think it would be easiest if you could just push them again. Otherwise, I will try to find some time this week to redo what you suggest. Thanks!

Yep but I'm not quite sure I have time to do it.

**Review by francbartoli — CHANGES_REQUESTED** [review]
Also here https://github.com/GeoNode/geonode-project/blob/2.10.x/tasks.py#L57:

```shell
        "docker_env": os.environ.get('DOCKER_ENV', 'production'),
```

**Comment by francbartoli** [comment]
And I have removed the celery service from the override of development for now

**Comment by t-book** [comment]
> > @francbartoli do you still have those files locally? If so I think it would be easiest if you could just push them again. Otherwise, I will try to find some time this week to redo what you suggest. Thanks!
> 
> Yep but I'm not quite sure I have time to do it.

@francbartoli  To prevent misunderstandings: 
- In case you have working development-compose files locally I would prefer to wait. You could also just send them to me and I care about integration.
- In case you do not have working files I would try to find some time to build them based on your comments. (can take a bit)

**Comment by afabiani** [comment]
@t-book @francbartoli can we merge this one?

**Comment by francbartoli** [comment]
@afabiani I think the PR isn't complete to have it working well

**Comment by t-book** [comment]
@afabiani this PR would restore the files but unfortunately, this is not all it takes to make it working again. So no, not ready to merge.

**Comment by t-book** [comment]
Here is still some work to do. I hope to find some time to test what is missing for development setup

**Comment by t-book** [comment]
I will close here and reopen when there is progress.

**Pull request closed without merging**
