### PR TITLE
 - Full production stack configuration: GeoFence, Celery Tasks and Contrib Apps

### PR DESCRIPTION
**Pull request by afabiani**
Adding automatic full-stack containers to "geonode-project" template:

 - Celery and RabbitMQ; allows to add automatic tasks, like:
      ```
        CELERY_BEAT_SCHEDULE['dispatch_metrics'] = {
                'task': 'geonode_logstash.tasks.dispatch_metrics',
                'schedule': 3600.0,
        }
      ```

- Configuration of GeoFence in order to store the rules into the "db" container instead of H2

### CODE REVIEW

**Comment by t-book** [comment]
ahh nice @afabiani  ! give me a second to test it!

**Comment by afabiani** [comment]
@t-book just found a typo on geoserver docker container. 

Committing the fix now

**Comment by afabiani** [comment]
@t-book fixed and enabled marling renderer from java opts by default on .env

@giohappy CENTRALIZED_DASHBOARD now False by default

**Review by giohappy — APPROVED** [review]

**Comment by t-book** [comment]
@afabiani you kindly added contrib apps. Would it hurt to add `libldap2-dev libsasl2-dev` to the dockerfile? Doing so we could use ldap contrib app right away.

**Comment by afabiani** [comment]
Sure @t-book even though I haven't tested LDAP contribs apps with Py3 yet... will spend some time on that in the next days

**Comment by t-book** [comment]
great, I will most likely work on it as well coming week. In case I run into troubles I'll let you know otherwise I would try to add some lines to docs for docker with ldap.

Regarding testing unfortunately I've forgotten to add ,properties to the django-admin command. need to rebuild all containers again. As @giohappy already approved feel free to merge as this might take another 30 minutes.

**Comment by afabiani** [comment]
@t-book no worries, will merge after having some results from LDAP stuff too

**Comment by giohappy** [comment]
@t-book take your time to test it. I'd prefer to have also your feedbacks before merging.

**Comment by t-book** [comment]
geonode-project@docker just makes it to my number 1 install methods for geonode ;)

**Comment by t-book** [comment]
@afabiani back and tested. Your changes are as always well done and do work for me. 
Where I'm unsure is if I've seen this error before:

`docker-compose logs -f`

```
my_geonode_letsencrypt_1 exited with code 1
ERROR: An HTTP request took too long to complete. Retry with --verbose to obtain debug information.
If you encounter this issue regularly because of slow network conditions, consider setting COMPOSE_HTTP_TIMEOUT to a higher value (current value: 60).
```

Mainly the HTTP Timeout occurs repeatedly, I'm unsure if it's really the le container which throws this error. Even more strange as le is disabled by default in .env

**Review by t-book — APPROVED** [review]

**Comment by gannebamm** [comment]
Could we have these for the main geonode docker, too?

I would do so myself, but am currently busy *!

**Comment by afabiani** [comment]
@gannebamm yeps ok, I'll provide a PR on GeoNode for that.

**Pull request merged**
