### PR TITLE
Fix certbot staging certificate generation

### LINKED ISSUE #203: certbot fails when using LETSENCRYPT_MODE=staging
```
Trying to get STAGING certificate
--server value conflicts with --staging
 
Failed to get the certificates !
```

https://github.com/GeoNode/geonode-project/blob/e21cc1b398fe1b46042c766bfc276b798f11d4de/docker/letsencrypt/docker-entrypoint.sh#L20

https://acme-staging-v02.api.letsencrypt.org/directory should be used instead, according to https://letsencrypt.org/docs/staging-environment/.

### PR DESCRIPTION
**Pull request by frafra**
Fix #203.

### CODE REVIEW

**Comment by lpasquali** [comment]
@frafra, many thanks for this PR

I think that a better foreseeing fix might be try to remove --staging in staging and the whole --server option for both prod and staging  and use --dry-run option in certbot for staging certificates. This way we will not depend anymore on ACME host names changes (see https://letsencrypt.org/docs/staging-environment/)

**Comment by frafra** [comment]
@lpasquali Ok! I would then suggest renaming "STAGING" to "DRYRUN" to avoid confusion (as different certificates will be served over HTTPS).

**Comment by lpasquali** [comment]
> @lpasquali Ok! I would then suggest renaming "STAGING" to "DRYRUN" to avoid confusion (as different certificates will be served over HTTPS).

well it is still staging stating at the current doc I pasted, the option `--dry-run` uses staging ACME environment, we'd just need to update to a simpler configuration the certbot commands and since --dryrun does stating certs, I'm unsure this would be a real benefit in avoiding confusion

**Comment by frafra** [comment]
> > @lpasquali Ok! I would then suggest renaming "STAGING" to "DRYRUN" to avoid confusion (as different certificates will be served over HTTPS).
> 
> well it is still staging stating at the current doc I pasted, the option `--dry-run` uses staging ACME environment, we'd just need to update to a simpler configuration the certbot commands and since --dryrun does stating certs, I'm unsure this would be a real benefit in avoiding confusion

>   --dry-run             Perform a test run of the client, obtaining test
>                        (invalid) certificates but not saving them to disk.

-- https://certbot.eff.org/docs/using.html?highlight=--dry-run#certbot-command-line-options

It is my understanding that a GeoNode instance with set to "STAGING" will not get SSL certificates at all then, so it would rely on local self-signed certificates if available. That would break many browsers, probably.

**Comment by lpasquali** [comment]
> > > @lpasquali Ok! I would then suggest renaming "STAGING" to "DRYRUN" to avoid confusion (as different certificates will be served over HTTPS).
> > 
> > 
> > well it is still staging stating at the current doc I pasted, the option `--dry-run` uses staging ACME environment, we'd just need to update to a simpler configuration the certbot commands and since --dryrun does stating certs, I'm unsure this would be a real benefit in avoiding confusion
> 
> > --dry-run             Perform a test run of the client, obtaining test
> > (invalid) certificates but not saving them to disk.
> 
> -- https://certbot.eff.org/docs/using.html?highlight=--dry-run#certbot-command-line-options
> 
> It is my understanding that a GeoNode instance with set to "STAGING" will not get SSL certificates at all then, so it would rely on local self-signed certificates if available. That would break many browsers, probably.

@frafra I beg your pardon, I wanted to mean "--test-cert" (--staging is left for backward compatibility) , "--dry-run" is not to be used in our case.

**Comment by frafra** [comment]
> @frafra I beg your pardon, I wanted to mean "--test-cert" (--staging is left for backward compatibility) , "--dry-run" is not to be used in our case.

Ok! Great then :)
I updated my branch.

**Comment by afabiani** [comment]
@lpasquali if it's ok with you we can merge then

**Review by lpasquali — APPROVED** [review]

**Comment by lpasquali** [comment]
> @lpasquali if it's ok with you we can merge then

changes approved @afabiani

**Pull request merged**
