### PR TITLE
 Adding local_settings template

### PR DESCRIPTION
**Pull request by afabiani**
@simod can you please merge this PR?

### CODE REVIEW

**Comment by simod** [comment]
@afabiani ok. Is there any chance to avoid to duplicate all Geonode settings in there?

**Comment by pjdufour** [comment]
If I can kindly do so, I'd like to provide my understanding of "our" best practice approach to the "SETTINGS issue".  Although last I discussed with anyone was in January I think.

In order of precedence are: (1) `environmental variables`, (2) `local_settings.py`, (3) `settings.py`.

Only `settings.py` is versioned in the downstream project repo.  `local_settings.py` is added by ansible or the provisioner as needed.  However, since it's not tracked by git it doesn't prevent `git pull` to update production systems, b/c local changes.  If local_settings.py is added to this or other downstream repos it will break those automated deployment workflows.

local_settings.py should only be used for settings that you we haven't properly made compatible with environmental variables, b/c they are python dicts, etc.  It should not duplicate the `settings.py` in `geonode-project`.  To see how to make settings compatible with environment variables, see https://github.com/GeoNode/geonode/commit/5018bd7183865d034822440db1cb6a844f31a8d8.  I needed to set `OGC_SERVER_DEFAULT_PASSWORD` as an environmental variable, so I made it a string variable that then gets added to the dict below.

Lastly, the reason why `<downstreamproject>.settings.py` duplicates `geonode.settings.py` is to avoid circular imports and keep a clean execuation path.  WSGI, guinicorn, etc. will all properly load the settings with `django.conf import settings` as long as there aren't these weird dependencies between files.  You can see in the file below for example, that `ftf_geonode` appears in context processors and other places where it would be infeasible to reference the downstream project from the community version.

https://github.com/ftf-geonode/ftf_geonode/blob/master/ftf_geonode/settings.py

This is of course purely my opinion, so I may be out of date or wrong.  This is complex stuff.

**Comment by afabiani** [comment]
@simod @pjdufour you are right. I removed old template and added a clean local_settings.py

Can you please double check and eventually merge the PR?

**Comment by kalxas** [comment]
I had the impression that settings.py was before local_settings.py.
So now settings.py in master repo gets ignored?

**Comment by kalxas** [comment]
the ansible installer copies a new local_settings.py which is maintained here:
https://github.com/GeoNode/ansible-geonode/blob/master/templates/local_settings.py.j2

**Comment by kalxas** [comment]
@simod @afabiani @pjdufour @jj0hns0n @ingenieroariel the current state does not look ok to me:
1. wsgi app loads `{{ project_name }}.settings` in https://github.com/GeoNode/geonode-project/blob/master/project_name/wsgi.py#L18
2. `{{ project_name }}.settings` then loads `local_settings` in https://github.com/GeoNode/geonode-project/blob/master/project_name/settings.py#L1132
3. `local_settings` load `geonode.settings` in https://github.com/GeoNode/geonode-project/blob/master/project_name/local_settings.py#L23
4. `geonode.settings` re-define everything that already exists in `{{ project_name }}.settings`

I think we have to make a cleaner solution here and choose to ignore `geonode.settings` as in branch 2.6.

Thoughts?

**Comment by pjdufour** [comment]
Oh.... IMHO, I wouldn't think `{{ project_name }}.local_settings` should have any imports period.  `{{ project_name }}.settings` imports `{{ project_name }}.local_settings` not the other way around (b/c that's what Django expects).  Otherwise `django.conf import settings` may have unexpected results.

**Comment by ingenieroariel** [comment]
In my opinion there are only two clean ways to override settings:

1. Environment variables if it is things like database name, etc.
2. {myproject}.settings if it needs to tweak installed apps or do any serious customization.

The local_settings approch was a very widespread Django practice that should not be considered best practice precisely because of the circular import problems it causes.

I see no need to import geonode.settings anywhere, that just sets up downstream projects from potential problems during upgrades.

-a

**Comment by simod** [comment]
We could also avoid the use of a local_settings in the project. As it is a local custom project the settings.py should be enough (it was like this in the past too). @ingenieroariel importing from geonode.settings in myproject.settings is what allows to do things like collectstatic and keeping the db of an original geonode installation like with apt-get. How would you keep that?

**Comment by ingenieroariel** [comment]
The original geonode should take the path that collect static uses as an env var, same for the db config.

The downstream projects gets the value from the same place. No need to import geonode.settings

-a

**Comment by simod** [comment]
Right, so the installer(s) should take care of setting them.+1

**Pull request merged**
